### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by eigenein** [eigenein/ns-bot#22]
Probably need to check HTTP status there:

```
Traceback (most recent call last):
  File "bot.py", line 568, in run
    await self.run_loop()
  File "bot.py", line 583, in run_loop
    updates = await self.telegram.get_updates(self.offset, self.TELEGRAM_LIMIT, self.TELEGRAM_TIMEOUT)
  File "bot.py", line 227, in get_updates
    return await self.post("getUpdates", offset=offset, limit=limit, timeout=timeout)
  File "bot.py", line 318, in post
    payload = await response.json()
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client_reqrep.py", line 761, in json
    return loads(stripped.decode(encoding))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by eigenein** [comment]
Лучше всего обработать это в eigenein/aiotg.
